name: vakhtovik_player
description: Плеер Вахтовика — кроссплатформенный клиент
publish_to: 'none'
version: 0.2.57

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_inappwebview: ^6.0.0
  package_info_plus: ^8.0.0
  webview_flutter: ^4.5.0
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  url_launcher: ^6.3.1
  path_provider: ^2.1.0
  window_manager: ^0.4.3
  shared_preferences: ^2.3.2
  crypto: ^3.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/iptv/
